# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0b925086f3aadee85a4319eedf923043fd8c0069d31a0ae3b496c28143d72b5c2ee93901d58218b66a757e9a1e09796a9ed841082182f0b6187b5a4848ced48

test:
  secret_key_base: 4d6cc140c093f46e3694deb2658487334cfc2a0fade79b05075926ae6406f98f4113ca8a75145335795ab424d172f5cbb5543eb4abdff9a17abf57de419ccdaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmail_username: 'shweta.hunagund@gmail.com'
gmail_password: 'Govi2435017'
